---
debug: true
# ginReleaseMode: true
port: 9999
gRPCPort: 8888
useTLS: true
tlsCertFile: "./localhost.crt"
tlsKeyFile: "./localhost.key"
dbType: "postgres" # or "mysql"
dbHost: "localhost"
dbPort: 5432 # or 3306 for "mysql"
dbName: "<your-db-name>"
dbUser: "<your-db-user>"
dbPassword: "<your-db-password>"
dbSSLMode: "disable"
ldapURL: "ldap://localhost:3893"
ldapBaseDN: "DC=example,DC=com"
ldapBindDN: "CN=JohnDoe,OU=users,DC=example,DC=com"
ldapBindPassword: "<your-ldap-password>"
ldapUsersGroupDN: "ou=Users,ou=users,dc=example,dc=com"
ldapServicesGroupDN: "ou=Services,ou=users,dc=example,dc=com"
ldapAdminsGroupDN: "ou=Admins,ou=users,dc=example,dc=com"
ldapFilterUser: "(&(objectClass=posixAccount)(uid={user}))"
ldapFilterGroup: "(&(objectClass=posixGroup)(memberUid={user}))"
# Active Directory
# ldapFilterUser: "(&(objectClass=user)(sAMAccountname={user}))"
# ldapFilterGroup: "(&(objectClass=group)(memberUid={user}))"
tokenValidInSeconds: 1800 # seconds
heartbeatCheckInSeconds: 30
