-- create "areas" table
CREATE TABLE "areas" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "description" character varying NOT NULL, PRIMARY KEY ("id"));
-- create index "areas_name_key" to table: "areas"
CREATE UNIQUE INDEX "areas_name_key" ON "areas" ("name");
-- create "services" table
CREATE TABLE "services" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "description" character varying NOT NULL, "protocol" character varying NOT NULL, "host" character varying NOT NULL, "port" character varying NOT NULL, "area_services" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "services_areas_services" FOREIGN KEY ("area_services") REFERENCES "areas" ("id") ON DELETE SET NULL);
