-- create "areas" table
CREATE TABLE "areas" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "description" character varying NOT NULL, PRIMARY KEY ("id"));
-- create index "areas_name_key" to table: "areas"
CREATE UNIQUE INDEX "areas_name_key" ON "areas" ("name");
-- create "tokens" table
CREATE TABLE "tokens" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "user" character varying NOT NULL, "token" character varying NOT NULL, "created" timestamptz NOT NULL, "permissions" bigint NOT NULL, PRIMARY KEY ("id"));
-- create index "tokens_user_key" to table: "tokens"
CREATE UNIQUE INDEX "tokens_user_key" ON "tokens" ("user");
-- create "services" table
CREATE TABLE "services" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "description" character varying NULL DEFAULT '', "protocol" character varying NOT NULL, "host" character varying NOT NULL, "port" character varying NOT NULL, "available" boolean NOT NULL DEFAULT false, "heartbeat" timestamptz NOT NULL, "area_services" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "services_areas_services" FOREIGN KEY ("area_services") REFERENCES "areas" ("id") ON DELETE SET NULL);
-- create "tags" table
CREATE TABLE "tags" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- create index "tags_name_key" to table: "tags"
CREATE UNIQUE INDEX "tags_name_key" ON "tags" ("name");
-- create "service_tags" table
CREATE TABLE "service_tags" ("service_id" bigint NOT NULL, "tag_id" bigint NOT NULL, PRIMARY KEY ("service_id", "tag_id"), CONSTRAINT "service_tags_service_id" FOREIGN KEY ("service_id") REFERENCES "services" ("id") ON DELETE CASCADE, CONSTRAINT "service_tags_tag_id" FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") ON DELETE CASCADE);
