-- create "areas" table
CREATE TABLE "areas" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "description" character varying NOT NULL, PRIMARY KEY ("id"));
-- create index "areas_name_key" to table: "areas"
CREATE UNIQUE INDEX "areas_name_key" ON "areas" ("name");
-- create "services" table
CREATE TABLE "services" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "description" character varying NULL DEFAULT '', "protocol" character varying NOT NULL, "host" character varying NOT NULL, "port" character varying NOT NULL, "area_services" bigint NULL, PRIMARY KEY ("id"));
-- create "tags" table
CREATE TABLE "tags" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- create index "tags_name_key" to table: "tags"
CREATE UNIQUE INDEX "tags_name_key" ON "tags" ("name");
-- create "tokens" table
CREATE TABLE "tokens" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "user" character varying NOT NULL, "token" character varying NOT NULL, "created" timestamptz NOT NULL, "admin" boolean NOT NULL DEFAULT false, PRIMARY KEY ("id"));
-- create index "tokens_user_key" to table: "tokens"
CREATE UNIQUE INDEX "tokens_user_key" ON "tokens" ("user");
-- create "service_tags" table
CREATE TABLE "service_tags" ("service_id" bigint NOT NULL, "tag_id" bigint NOT NULL, PRIMARY KEY ("service_id", "tag_id"));
