// Code generated by ent, DO NOT EDIT.

package ent

import (
	"sisco/ent/schema"
	"sisco/ent/service"
	"sisco/ent/token"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	serviceFields := schema.Service{}.Fields()
	_ = serviceFields
	// serviceDescDescription is the schema descriptor for description field.
	serviceDescDescription := serviceFields[1].Descriptor()
	// service.DefaultDescription holds the default value on creation for the description field.
	service.DefaultDescription = serviceDescDescription.Default.(string)
	// serviceDescAvailable is the schema descriptor for available field.
	serviceDescAvailable := serviceFields[5].Descriptor()
	// service.DefaultAvailable holds the default value on creation for the available field.
	service.DefaultAvailable = serviceDescAvailable.Default.(bool)
	// serviceDescHeartbeat is the schema descriptor for heartbeat field.
	serviceDescHeartbeat := serviceFields[6].Descriptor()
	// service.DefaultHeartbeat holds the default value on creation for the heartbeat field.
	service.DefaultHeartbeat = serviceDescHeartbeat.Default.(time.Time)
	tokenFields := schema.Token{}.Fields()
	_ = tokenFields
	// tokenDescCreated is the schema descriptor for created field.
	tokenDescCreated := tokenFields[2].Descriptor()
	// token.DefaultCreated holds the default value on creation for the created field.
	token.DefaultCreated = tokenDescCreated.Default.(time.Time)
}
